"""Add announcements table

Revision ID: 726a2d682e97
Revises: d1ff6b177f02
Create Date: 2025-11-01 10:50:04.376682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '726a2d682e97'
down_revision = 'd1ff6b177f02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expire_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dorm_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dorm_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('environment_rating', sa.Integer(), nullable=True),
    sa.Column('facilities_rating', sa.Integer(), nullable=True),
    sa.Column('location_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dorm_id'], ['dormitories.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dorm_reviews')
    op.drop_table('announcements')
    # ### end Alembic commands ###
